In [1]:
#1dimension
import numpy as np#import numpy
arr1=([11,2,3,4])
arr1

[11, 2, 3, 4]

In [2]:
arr2=np.arange(4)#array creation
arr2

array([0, 1, 2, 3])

In [3]:
arr3=arr1+arr2#add of 1d array
arr3

array([11,  3,  5,  7])

In [6]:
arr4=arr3+np.arange(3)#add gives value error
arr4

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [8]:
arr5=arr3+np.arange(4)#add
arr5

array([11,  4,  7, 10])

In [18]:
a=arr2*3#multiplication of array
a

array([0, 3, 6, 9])

In [22]:
b=arr2**2#square
b


array([0, 1, 4, 9], dtype=int32)

In [17]:
np.power(arr2,4)#power

array([ 0,  1, 16, 81], dtype=int32)

In [14]:
a1=arr2>=2#conditional expression-gives boolean
a1

array([False, False,  True,  True])

In [15]:
arr2[a1]#boolean if true prints the value

array([2, 3])

In [16]:
arr2[arr2>=2]#boolean if true prints the value

array([2, 3])

In [23]:
c=arr2**3#cubic
c


array([ 0,  1,  8, 27], dtype=int32)

In [24]:
d=arr2**4#power
d

array([ 0,  1, 16, 81], dtype=int32)